export const products = [
  {
    id: 1,
    name: 'Revitalizing Shampoo',
    description: 'Restore shine and bounce to dull hair',
    price: 16.99,
    image: 'https://placehold.co/500x500/FFF5E1/666666.png?text=Revitalizing+Shampoo',
    bgGradient: 'bg-gradient-to-r from-kira-pink to-kira-lavender bg-opacity-50',
    badge: 'NEW',
    badgeColor: 'bg-kira-coral',
  },
  {
    id: 2,
    name: 'Smoothing Conditioner',
    description: 'Tame frizz for silky, manageable hair',
    price: 14.99,
    image: 'https://placehold.co/500x500/E1FFF5/666666.png?text=Smoothing+Conditioner',
    bgGradient: 'bg-gradient-to-r from-kira-lavender to-kira-pink bg-opacity-50',
    badge: 'POPULAR',
    badgeColor: 'bg-kira-purple',
  },
  {
    id: 3,
    name: 'Hydrating Hair Mask',
    description: 'Deep conditioning for damaged hair',
    price: 19.99,
    image: 'https://placehold.co/500x500/FFE1F5/666666.png?text=Hydrating+Hair+Mask',
    bgGradient: 'bg-gradient-to-r from-kira-pink to-kira-lavender bg-opacity-50',
  },
  {
    id: 4,
    name: 'Volumizing Spray',
    description: 'Add lift and body to fine hair',
    price: 12.99,
    oldPrice: 15.99,
    image: 'https://placehold.co/500x500/F5FFE1/666666.png?text=Volumizing+Spray',
    bgGradient: 'bg-gradient-to-r from-kira-lavender to-kira-pink bg-opacity-50',
    badge: 'SALE',
    badgeColor: 'bg-kira-coral',
  },
];

export const testimonials = [
  {
    id: 1,
    quote: "I've tried so many products for my curly hair, but Kira's Hydrating Hair Mask is the first one that truly makes a difference. My curls are bouncy and defined!",
    authorName: "Emily R.",
    authorImage: "https://placehold.co/100x100/E1F5FF/666666.png?text=Emily+R",
    rating: 5,
    halfStar: false,
    quoteBoxColor: "bg-kira-pink",
  },
  {
    id: 2,
    quote: "The Revitalizing Shampoo smells amazing and makes my hair super soft. My friends keep asking what I'm using now. Love it!",
    authorName: "Sophia T.",
    authorImage: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?ixlib=rb-1.2.1&auto=format&fit=crop&w=100&q=80",
    rating: 4,
    halfStar: true,
    quoteBoxColor: "bg-kira-lavender",
  },
  {
    id: 3,
    quote: "Finally found products that don't weigh down my fine hair! The Volumizing Spray gives me the perfect lift without making my hair sticky.",
    authorName: "Madison K.",
    authorImage: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?ixlib=rb-1.2.1&auto=format&fit=crop&w=100&q=80",
    rating: 5,
    halfStar: false,
    quoteBoxColor: "bg-kira-coral",
  },
];
